### ISSUE TITLE
[as2_python_api] <NoModuleFound: No module named 'as2_python_api.modules'> 

### ISSUE THREAD

**Issue by str1x0** [aerostack2/aerostack2#374]
### ROS2 Version

humble

### Version

main

### What happened?

When loading the command:
`ros2 launch as2_keyboard_teleoperation as2_keyboard_teleoperation_launch.py namespace:=drone_sim_0,drone_sim_1,drone_sim_2 use_sim_time:=true`
it gives the error that:
`NoModuleFound: No module named `'as2_python_api.modules'

### Relevant log output

```shell
pc@pc-VB:~/aerostack2_ws/project_gazebo$ ros2 launch as2_keyboard_teleoperation as2_keyboard_teleoperation_launch.py          namespace:=drone_sim_0,drone_sim_1,drone_sim_2         use_sim_time:=true

[INFO] [launch]: All log files can be found below /home/pc/.ros/log/2023-12-17-13-27-58-278768-pc-VB-3068

[INFO] [launch]: Default logging verbosity is set to INFO

[INFO] [as2_keyboard_teleoperation-1]: process started with pid [3069]

[as2_keyboard_teleoperation-1] Traceback (most recent call last):

[as2_keyboard_teleoperation-1]   File "/opt/ros/humble/share/as2_keyboard_teleoperation/keyboard_teleoperation.py", line 42, in <module>

[as2_keyboard_teleoperation-1]     from as2_python_api.drone_interface_teleop import DroneInterfaceTeleop as DroneInterface

[as2_keyboard_teleoperation-1]   File "/opt/ros/humble/lib/python3.10/site-packages/as2_python_api/drone_interface_teleop.py", line 37, in <module>

[as2_keyboard_teleoperation-1]     from as2_python_api.drone_interface import DroneInterface

[as2_keyboard_teleoperation-1]   File "/opt/ros/humble/lib/python3.10/site-packages/as2_python_api/drone_interface.py", line 37, in <module>

[as2_keyboard_teleoperation-1]     from as2_python_api.modules.takeoff_module import TakeoffModule

[as2_keyboard_teleoperation-1] ModuleNotFoundError: No module named 'as2_python_api.modules'

[ERROR] [as2_keyboard_teleoperation-1]: process has died [pid 3069, exit code 1, cmd 'python3 /opt/ros/humble/share/as2_keyboard_teleoperation/keyboard_teleoperation.py drone_sim_0,drone_sim_1,drone_sim_2 false true'].
```

**Comment by RPS98** [comment]
Hi @str1x0,

How have you installed Aerostack2?
